#!/usr/bin/env bash

echo "This script list an S3 bucket object using AWS CLI."

# Check if bucket name is provided
if [ -z "$1" ]; then
  echo "Usage: $0 <bucket-name>"
  exit 1
fi

BUCKET_NAME=$1

echo "list S3 bucket Object: $BUCKET_NAME"
awslocal s3api list-objects \
--bucket $BUCKET_NAME \
--query Contents[].Key \
--output table
