#!/usr/bin/env bash

#this scirpt upload file to s3 bucket one file at a time

if [ -z "$1" ]; then
  echo "Usage: $0 <bucket-name>"
  exit 1
fi
bucket= $1
key= $2
body= $3

awslocal s3api put-object --bucket $bucket --key $key --body $body